package main

import "fmt"

func main() {
	// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	//		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

	set := [...]int{1, 2}
	sum := 0

	for set[0] < 4e6 {
		total := set[0] + set[1]

		set[0] = set[1]
		set[1] = total

		if total%2 == 0 {
			sum += total
		}
	}

	fmt.Println("The sum of the even-valued terms are: %d", sum)
}
